//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.10 at 09:34:41 PM CST 
//


package org.fbi.mbp.proxy.domain.sbs.transactrequest;

import org.fbi.mbp.proxy.domain.sbs.*;
import org.fbi.mbp.proxy.domain.sbs.ClientReqestRoot;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ToReserved4_QNAME = new QName("", "ToReserved4");
    private final static QName _ToReserved3_QNAME = new QName("", "ToReserved3");
    private final static QName _ToAccount_QNAME = new QName("", "ToAccount");
    private final static QName _FromReserved2_QNAME = new QName("", "FromReserved2");
    private final static QName _FromReserved3_QNAME = new QName("", "FromReserved3");
    private final static QName _FromReserved4_QNAME = new QName("", "FromReserved4");
    private final static QName _Usage_QNAME = new QName("", "Usage");
    private final static QName _FromBank_QNAME = new QName("", "FromBank");
    private final static QName _Internal_QNAME = new QName("", "Internal");
    private final static QName _System_QNAME = new QName("", "System");
    private final static QName _Currency_QNAME = new QName("", "Currency");
    private final static QName _ToReserved1_QNAME = new QName("", "ToReserved1");
    private final static QName _Public_QNAME = new QName("", "Public");
    private final static QName _TransDate_QNAME = new QName("", "TransDate");
    private final static QName _ToReserved2_QNAME = new QName("", "ToReserved2");
    private final static QName _OpName_QNAME = new QName("", "OpName");
    private final static QName _Amount_QNAME = new QName("", "Amount");
    private final static QName _Local_QNAME = new QName("", "Local");
    private final static QName _OpID_QNAME = new QName("", "OpID");
    private final static QName _Bank_QNAME = new QName("", "Bank");
    private final static QName _ToBank_QNAME = new QName("", "ToBank");
    private final static QName _ToName_QNAME = new QName("", "ToName");
    private final static QName _Reserved1_QNAME = new QName("", "Reserved1");
    private final static QName _OpEntID_QNAME = new QName("", "OpEntID");
    private final static QName _Reserved3_QNAME = new QName("", "Reserved3");
    private final static QName _Speed_QNAME = new QName("", "Speed");
    private final static QName _OpBankCode_QNAME = new QName("", "OpBankCode");
    private final static QName _FromAccount_QNAME = new QName("", "FromAccount");
    private final static QName _Reserved2_QNAME = new QName("", "Reserved2");
    private final static QName _EnterpriseSerial_QNAME = new QName("", "EnterpriseSerial");
    private final static QName _FromReserved1_QNAME = new QName("", "FromReserved1");
    private final static QName _Reserved4_QNAME = new QName("", "Reserved4");
    private final static QName _FromName_QNAME = new QName("", "FromName");
    private final static QName _OpDate_QNAME = new QName("", "OpDate");
    private final static QName _VoucherNum_QNAME = new QName("", "VoucherNum");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link org.fbi.mbp.proxy.domain.sbs.ClientReqestRoot }
     * 
     */
    public ClientReqestRoot createRoot() {
        return new ClientReqestRoot();
    }

    /**
     * Create an instance of {@link org.fbi.mbp.proxy.domain.sbs.ClientReqestHead }
     * 
     */
    public ClientReqestHead createHead() {
        return new ClientReqestHead();
    }

    /**
     * Create an instance of {@link TransactParam }
     * 
     */
    public TransactParam createParam() {
        return new TransactParam();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToReserved4")
    public JAXBElement<String> createToReserved4(String value) {
        return new JAXBElement<String>(_ToReserved4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToReserved3")
    public JAXBElement<String> createToReserved3(String value) {
        return new JAXBElement<String>(_ToReserved3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToAccount")
    public JAXBElement<String> createToAccount(String value) {
        return new JAXBElement<String>(_ToAccount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromReserved2")
    public JAXBElement<String> createFromReserved2(String value) {
        return new JAXBElement<String>(_FromReserved2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromReserved3")
    public JAXBElement<String> createFromReserved3(String value) {
        return new JAXBElement<String>(_FromReserved3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromReserved4")
    public JAXBElement<String> createFromReserved4(String value) {
        return new JAXBElement<String>(_FromReserved4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Usage")
    public JAXBElement<String> createUsage(String value) {
        return new JAXBElement<String>(_Usage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromBank")
    public JAXBElement<String> createFromBank(String value) {
        return new JAXBElement<String>(_FromBank_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Internal")
    public JAXBElement<String> createInternal(String value) {
        return new JAXBElement<String>(_Internal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "System")
    public JAXBElement<String> createSystem(String value) {
        return new JAXBElement<String>(_System_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Currency")
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToReserved1")
    public JAXBElement<String> createToReserved1(String value) {
        return new JAXBElement<String>(_ToReserved1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Public")
    public JAXBElement<String> createPublic(String value) {
        return new JAXBElement<String>(_Public_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransDate")
    public JAXBElement<String> createTransDate(String value) {
        return new JAXBElement<String>(_TransDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToReserved2")
    public JAXBElement<String> createToReserved2(String value) {
        return new JAXBElement<String>(_ToReserved2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpName")
    public JAXBElement<String> createOpName(String value) {
        return new JAXBElement<String>(_OpName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Amount")
    public JAXBElement<String> createAmount(String value) {
        return new JAXBElement<String>(_Amount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Local")
    public JAXBElement<String> createLocal(String value) {
        return new JAXBElement<String>(_Local_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpID")
    public JAXBElement<String> createOpID(String value) {
        return new JAXBElement<String>(_OpID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Bank")
    public JAXBElement<String> createBank(String value) {
        return new JAXBElement<String>(_Bank_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToBank")
    public JAXBElement<String> createToBank(String value) {
        return new JAXBElement<String>(_ToBank_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ToName")
    public JAXBElement<String> createToName(String value) {
        return new JAXBElement<String>(_ToName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reserved1")
    public JAXBElement<String> createReserved1(String value) {
        return new JAXBElement<String>(_Reserved1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpEntID")
    public JAXBElement<String> createOpEntID(String value) {
        return new JAXBElement<String>(_OpEntID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reserved3")
    public JAXBElement<String> createReserved3(String value) {
        return new JAXBElement<String>(_Reserved3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Speed")
    public JAXBElement<String> createSpeed(String value) {
        return new JAXBElement<String>(_Speed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpBankCode")
    public JAXBElement<String> createOpBankCode(String value) {
        return new JAXBElement<String>(_OpBankCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromAccount")
    public JAXBElement<String> createFromAccount(String value) {
        return new JAXBElement<String>(_FromAccount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reserved2")
    public JAXBElement<String> createReserved2(String value) {
        return new JAXBElement<String>(_Reserved2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EnterpriseSerial")
    public JAXBElement<String> createEnterpriseSerial(String value) {
        return new JAXBElement<String>(_EnterpriseSerial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromReserved1")
    public JAXBElement<String> createFromReserved1(String value) {
        return new JAXBElement<String>(_FromReserved1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reserved4")
    public JAXBElement<String> createReserved4(String value) {
        return new JAXBElement<String>(_Reserved4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FromName")
    public JAXBElement<String> createFromName(String value) {
        return new JAXBElement<String>(_FromName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpDate")
    public JAXBElement<String> createOpDate(String value) {
        return new JAXBElement<String>(_OpDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VoucherNum")
    public JAXBElement<String> createVoucherNum(String value) {
        return new JAXBElement<String>(_VoucherNum_QNAME, String.class, null, value);
    }

}
