//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.10 at 09:34:41 PM CST 
//


package org.fbi.mbp.proxy.domain.sbs.transactrequest;

import org.fbi.mbp.proxy.domain.sbs.ClientReqestHead;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Head"/>
 *         &lt;element ref="{}Param"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "param"
})
@XmlRootElement(name = "root")
public class TransactRoot {

    @XmlElement(name = "Head", required = true)
    protected ClientReqestHead head;
    @XmlElement(name = "Param", required = true)
    protected TransactParam param;

    /**
     * Gets the value of the head property.
     *
     * @return
     *     possible object is
     *     {@link org.fbi.mbp.proxy.domain.sbs.ClientReqestHead }
     *
     */
    public ClientReqestHead getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     *
     * @param value
     *     allowed object is
     *     {@link org.fbi.mbp.proxy.domain.sbs.ClientReqestHead }
     *
     */
    public void setHead(ClientReqestHead value) {
        this.head = value;
    }

    /**
     * Gets the value of the param property.
     *
     * @return
     *     possible object is
     *     {@link org.fbi.mbp.proxy.domain.sbs.transactrequest.TransactParam }
     *
     */
    public TransactParam getParam() {
        return param;
    }

    /**
     * Sets the value of the param property.
     *
     * @param value
     *     allowed object is
     *     {@link org.fbi.mbp.proxy.domain.sbs.transactrequest.TransactParam }
     *     
     */
    public void setParam(TransactParam value) {
        this.param = value;
    }

    @Override
    public String toString() {
        return "Root{" +
                "head=" + head +
                ", param=" + param +
                '}';
    }
}
