//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.11 at 11:40:03 AM CST 
//


package org.fbi.mbp.proxy.domain.ccb.t2719response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Version"/>
 *         &lt;element ref="{}TxCode"/>
 *         &lt;element ref="{}FuncCode"/>
 *         &lt;element ref="{}Channel"/>
 *         &lt;element ref="{}SubCenterId"/>
 *         &lt;element ref="{}NodeId"/>
 *         &lt;element ref="{}TellerId"/>
 *         &lt;element ref="{}TxSeqId"/>
 *         &lt;element ref="{}TxDate"/>
 *         &lt;element ref="{}TxTime"/>
 *         &lt;element ref="{}UserId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "txCode",
    "funcCode",
    "channel",
    "subCenterId",
    "nodeId",
    "tellerId",
    "txSeqId",
    "txDate",
    "txTime",
    "userId"
})
@XmlRootElement(name = "Head")
public class Head {

    @XmlElement(name = "Version", required = true)
    protected String version;
    @XmlElement(name = "TxCode", required = true)
    protected String txCode;
    @XmlElement(name = "FuncCode", required = true)
    protected String funcCode;
    @XmlElement(name = "Channel", required = true)
    protected String channel;
    @XmlElement(name = "SubCenterId", required = true)
    protected String subCenterId;
    @XmlElement(name = "NodeId", required = true)
    protected String nodeId;
    @XmlElement(name = "TellerId", required = true)
    protected String tellerId;
    @XmlElement(name = "TxSeqId", required = true)
    protected String txSeqId;
    @XmlElement(name = "TxDate", required = true)
    protected String txDate;
    @XmlElement(name = "TxTime", required = true)
    protected String txTime;
    @XmlElement(name = "UserId", required = true)
    protected String userId;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the txCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxCode() {
        return txCode;
    }

    /**
     * Sets the value of the txCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxCode(String value) {
        this.txCode = value;
    }

    /**
     * Gets the value of the funcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuncCode() {
        return funcCode;
    }

    /**
     * Sets the value of the funcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuncCode(String value) {
        this.funcCode = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }

    /**
     * Gets the value of the subCenterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCenterId() {
        return subCenterId;
    }

    /**
     * Sets the value of the subCenterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCenterId(String value) {
        this.subCenterId = value;
    }

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeId(String value) {
        this.nodeId = value;
    }

    /**
     * Gets the value of the tellerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTellerId() {
        return tellerId;
    }

    /**
     * Sets the value of the tellerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTellerId(String value) {
        this.tellerId = value;
    }

    /**
     * Gets the value of the txSeqId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxSeqId() {
        return txSeqId;
    }

    /**
     * Sets the value of the txSeqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxSeqId(String value) {
        this.txSeqId = value;
    }

    /**
     * Gets the value of the txDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxDate() {
        return txDate;
    }

    /**
     * Sets the value of the txDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxDate(String value) {
        this.txDate = value;
    }

    /**
     * Gets the value of the txTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxTime() {
        return txTime;
    }

    /**
     * Sets the value of the txTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxTime(String value) {
        this.txTime = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

}
