//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.11 at 11:36:32 AM CST 
//


package org.fbi.mbp.proxy.domain.ccb.t2719request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CoSeqId"/>
 *         &lt;element ref="{}OperatorUserId"/>
 *         &lt;element ref="{}OutUserId"/>
 *         &lt;element ref="{}OutDepId"/>
 *         &lt;element ref="{}OutAcctId"/>
 *         &lt;element ref="{}OutAcctName"/>
 *         &lt;element ref="{}OutBranchName"/>
 *         &lt;element ref="{}QuotaAcctId"/>
 *         &lt;element ref="{}QuotaAcctName"/>
 *         &lt;element ref="{}InUserId"/>
 *         &lt;element ref="{}InDepId"/>
 *         &lt;element ref="{}InAcctId"/>
 *         &lt;element ref="{}InAcctName"/>
 *         &lt;element ref="{}InBranchName"/>
 *         &lt;element ref="{}InBranchId"/>
 *         &lt;element ref="{}BankFlag"/>
 *         &lt;element ref="{}TxAmount"/>
 *         &lt;element ref="{}Memo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coSeqId",
    "operatorUserId",
    "outUserId",
    "outDepId",
    "outAcctId",
    "outAcctName",
    "outBranchName",
    "quotaAcctId",
    "quotaAcctName",
    "inUserId",
    "inDepId",
    "inAcctId",
    "inAcctName",
    "inBranchName",
    "inBranchId",
    "bankFlag",
    "txAmount",
    "memo"
})
@XmlRootElement(name = "Body")
public class Body {

    @XmlElement(name = "CoSeqId", required = true)
    protected String coSeqId;
    @XmlElement(name = "OperatorUserId", required = true)
    protected String operatorUserId;
    @XmlElement(name = "OutUserId", required = true)
    protected String outUserId;
    @XmlElement(name = "OutDepId", required = true)
    protected String outDepId;
    @XmlElement(name = "OutAcctId", required = true)
    protected String outAcctId;
    @XmlElement(name = "OutAcctName", required = true)
    protected String outAcctName;
    @XmlElement(name = "OutBranchName", required = true)
    protected String outBranchName;
    @XmlElement(name = "QuotaAcctId", required = true)
    protected String quotaAcctId;
    @XmlElement(name = "QuotaAcctName", required = true)
    protected String quotaAcctName;
    @XmlElement(name = "InUserId", required = true)
    protected String inUserId;
    @XmlElement(name = "InDepId", required = true)
    protected String inDepId;
    @XmlElement(name = "InAcctId", required = true)
    protected String inAcctId;
    @XmlElement(name = "InAcctName", required = true)
    protected String inAcctName;
    @XmlElement(name = "InBranchName", required = true)
    protected String inBranchName;
    @XmlElement(name = "InBranchId", required = true)
    protected String inBranchId;
    @XmlElement(name = "BankFlag", required = true)
    protected String bankFlag;
    @XmlElement(name = "TxAmount", required = true)
    protected String txAmount;
    @XmlElement(name = "Memo", required = true)
    protected String memo;

    /**
     * Gets the value of the coSeqId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoSeqId() {
        return coSeqId;
    }

    /**
     * Sets the value of the coSeqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoSeqId(String value) {
        this.coSeqId = value;
    }

    /**
     * Gets the value of the operatorUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorUserId() {
        return operatorUserId;
    }

    /**
     * Sets the value of the operatorUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorUserId(String value) {
        this.operatorUserId = value;
    }

    /**
     * Gets the value of the outUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutUserId() {
        return outUserId;
    }

    /**
     * Sets the value of the outUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutUserId(String value) {
        this.outUserId = value;
    }

    /**
     * Gets the value of the outDepId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutDepId() {
        return outDepId;
    }

    /**
     * Sets the value of the outDepId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutDepId(String value) {
        this.outDepId = value;
    }

    /**
     * Gets the value of the outAcctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutAcctId() {
        return outAcctId;
    }

    /**
     * Sets the value of the outAcctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutAcctId(String value) {
        this.outAcctId = value;
    }

    /**
     * Gets the value of the outAcctName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutAcctName() {
        return outAcctName;
    }

    /**
     * Sets the value of the outAcctName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutAcctName(String value) {
        this.outAcctName = value;
    }

    /**
     * Gets the value of the outBranchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutBranchName() {
        return outBranchName;
    }

    /**
     * Sets the value of the outBranchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutBranchName(String value) {
        this.outBranchName = value;
    }

    /**
     * Gets the value of the quotaAcctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotaAcctId() {
        return quotaAcctId;
    }

    /**
     * Sets the value of the quotaAcctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotaAcctId(String value) {
        this.quotaAcctId = value;
    }

    /**
     * Gets the value of the quotaAcctName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotaAcctName() {
        return quotaAcctName;
    }

    /**
     * Sets the value of the quotaAcctName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotaAcctName(String value) {
        this.quotaAcctName = value;
    }

    /**
     * Gets the value of the inUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInUserId() {
        return inUserId;
    }

    /**
     * Sets the value of the inUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInUserId(String value) {
        this.inUserId = value;
    }

    /**
     * Gets the value of the inDepId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInDepId() {
        return inDepId;
    }

    /**
     * Sets the value of the inDepId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInDepId(String value) {
        this.inDepId = value;
    }

    /**
     * Gets the value of the inAcctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInAcctId() {
        return inAcctId;
    }

    /**
     * Sets the value of the inAcctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInAcctId(String value) {
        this.inAcctId = value;
    }

    /**
     * Gets the value of the inAcctName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInAcctName() {
        return inAcctName;
    }

    /**
     * Sets the value of the inAcctName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInAcctName(String value) {
        this.inAcctName = value;
    }

    /**
     * Gets the value of the inBranchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInBranchName() {
        return inBranchName;
    }

    /**
     * Sets the value of the inBranchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInBranchName(String value) {
        this.inBranchName = value;
    }

    /**
     * Gets the value of the inBranchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInBranchId() {
        return inBranchId;
    }

    /**
     * Sets the value of the inBranchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInBranchId(String value) {
        this.inBranchId = value;
    }

    /**
     * Gets the value of the bankFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankFlag() {
        return bankFlag;
    }

    /**
     * Sets the value of the bankFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankFlag(String value) {
        this.bankFlag = value;
    }

    /**
     * Gets the value of the txAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxAmount() {
        return txAmount;
    }

    /**
     * Sets the value of the txAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxAmount(String value) {
        this.txAmount = value;
    }

    /**
     * Gets the value of the memo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemo() {
        return memo;
    }

    /**
     * Sets the value of the memo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemo(String value) {
        this.memo = value;
    }

}
