//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.11 at 11:36:32 AM CST 
//


package org.fbi.mbp.proxy.domain.ccb.t2719request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Channel_QNAME = new QName("", "Channel");
    private final static QName _FuncCode_QNAME = new QName("", "FuncCode");
    private final static QName _InBranchId_QNAME = new QName("", "InBranchId");
    private final static QName _InDepId_QNAME = new QName("", "InDepId");
    private final static QName _OutAcctId_QNAME = new QName("", "OutAcctId");
    private final static QName _TxSeqId_QNAME = new QName("", "TxSeqId");
    private final static QName _NodeId_QNAME = new QName("", "NodeId");
    private final static QName _QuotaAcctName_QNAME = new QName("", "QuotaAcctName");
    private final static QName _Version_QNAME = new QName("", "Version");
    private final static QName _TxDate_QNAME = new QName("", "TxDate");
    private final static QName _BankFlag_QNAME = new QName("", "BankFlag");
    private final static QName _OutDepId_QNAME = new QName("", "OutDepId");
    private final static QName _OutBranchName_QNAME = new QName("", "OutBranchName");
    private final static QName _InUserId_QNAME = new QName("", "InUserId");
    private final static QName _InAcctId_QNAME = new QName("", "InAcctId");
    private final static QName _OutUserId_QNAME = new QName("", "OutUserId");
    private final static QName _UserId_QNAME = new QName("", "UserId");
    private final static QName _TellerId_QNAME = new QName("", "TellerId");
    private final static QName _CoSeqId_QNAME = new QName("", "CoSeqId");
    private final static QName _InAcctName_QNAME = new QName("", "InAcctName");
    private final static QName _OperatorUserId_QNAME = new QName("", "OperatorUserId");
    private final static QName _TxTime_QNAME = new QName("", "TxTime");
    private final static QName _Memo_QNAME = new QName("", "Memo");
    private final static QName _SubCenterId_QNAME = new QName("", "SubCenterId");
    private final static QName _TxCode_QNAME = new QName("", "TxCode");
    private final static QName _InBranchName_QNAME = new QName("", "InBranchName");
    private final static QName _QuotaAcctId_QNAME = new QName("", "QuotaAcctId");
    private final static QName _OutAcctName_QNAME = new QName("", "OutAcctName");
    private final static QName _TxAmount_QNAME = new QName("", "TxAmount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Channel")
    public JAXBElement<String> createChannel(String value) {
        return new JAXBElement<String>(_Channel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FuncCode")
    public JAXBElement<String> createFuncCode(String value) {
        return new JAXBElement<String>(_FuncCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InBranchId")
    public JAXBElement<String> createInBranchId(String value) {
        return new JAXBElement<String>(_InBranchId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InDepId")
    public JAXBElement<String> createInDepId(String value) {
        return new JAXBElement<String>(_InDepId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutAcctId")
    public JAXBElement<String> createOutAcctId(String value) {
        return new JAXBElement<String>(_OutAcctId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxSeqId")
    public JAXBElement<String> createTxSeqId(String value) {
        return new JAXBElement<String>(_TxSeqId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NodeId")
    public JAXBElement<String> createNodeId(String value) {
        return new JAXBElement<String>(_NodeId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuotaAcctName")
    public JAXBElement<String> createQuotaAcctName(String value) {
        return new JAXBElement<String>(_QuotaAcctName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxDate")
    public JAXBElement<String> createTxDate(String value) {
        return new JAXBElement<String>(_TxDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BankFlag")
    public JAXBElement<String> createBankFlag(String value) {
        return new JAXBElement<String>(_BankFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutDepId")
    public JAXBElement<String> createOutDepId(String value) {
        return new JAXBElement<String>(_OutDepId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutBranchName")
    public JAXBElement<String> createOutBranchName(String value) {
        return new JAXBElement<String>(_OutBranchName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InUserId")
    public JAXBElement<String> createInUserId(String value) {
        return new JAXBElement<String>(_InUserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InAcctId")
    public JAXBElement<String> createInAcctId(String value) {
        return new JAXBElement<String>(_InAcctId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutUserId")
    public JAXBElement<String> createOutUserId(String value) {
        return new JAXBElement<String>(_OutUserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserId")
    public JAXBElement<String> createUserId(String value) {
        return new JAXBElement<String>(_UserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TellerId")
    public JAXBElement<String> createTellerId(String value) {
        return new JAXBElement<String>(_TellerId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CoSeqId")
    public JAXBElement<String> createCoSeqId(String value) {
        return new JAXBElement<String>(_CoSeqId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InAcctName")
    public JAXBElement<String> createInAcctName(String value) {
        return new JAXBElement<String>(_InAcctName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OperatorUserId")
    public JAXBElement<String> createOperatorUserId(String value) {
        return new JAXBElement<String>(_OperatorUserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxTime")
    public JAXBElement<String> createTxTime(String value) {
        return new JAXBElement<String>(_TxTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Memo")
    public JAXBElement<String> createMemo(String value) {
        return new JAXBElement<String>(_Memo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubCenterId")
    public JAXBElement<String> createSubCenterId(String value) {
        return new JAXBElement<String>(_SubCenterId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxCode")
    public JAXBElement<String> createTxCode(String value) {
        return new JAXBElement<String>(_TxCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InBranchName")
    public JAXBElement<String> createInBranchName(String value) {
        return new JAXBElement<String>(_InBranchName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuotaAcctId")
    public JAXBElement<String> createQuotaAcctId(String value) {
        return new JAXBElement<String>(_QuotaAcctId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutAcctName")
    public JAXBElement<String> createOutAcctName(String value) {
        return new JAXBElement<String>(_OutAcctName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TxAmount")
    public JAXBElement<String> createTxAmount(String value) {
        return new JAXBElement<String>(_TxAmount_QNAME, String.class, null, value);
    }

}
