//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.11 at 11:30:53 AM CST 
//


package org.fbi.mbp.proxy.domain.sbs.transactreponse;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Reserved1_QNAME = new QName("", "Reserved1");
    private final static QName _OpRetCode_QNAME = new QName("", "OpRetCode");
    private final static QName _Result_QNAME = new QName("", "Result");
    private final static QName _Reserved3_QNAME = new QName("", "Reserved3");
    private final static QName _BankSerial_QNAME = new QName("", "BankSerial");
    private final static QName _Reserved2_QNAME = new QName("", "Reserved2");
    private final static QName _Reserved4_QNAME = new QName("", "Reserved4");
    private final static QName _OpRetMsg_QNAME = new QName("", "OpRetMsg");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reserved1")
    public JAXBElement<String> createReserved1(String value) {
        return new JAXBElement<String>(_Reserved1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link java.math.BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpRetCode")
    public JAXBElement<BigInteger> createOpRetCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_OpRetCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Result")
    public JAXBElement<String> createResult(String value) {
        return new JAXBElement<String>(_Result_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reserved3")
    public JAXBElement<String> createReserved3(String value) {
        return new JAXBElement<String>(_Reserved3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BankSerial")
    public JAXBElement<String> createBankSerial(String value) {
        return new JAXBElement<String>(_BankSerial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reserved2")
    public JAXBElement<String> createReserved2(String value) {
        return new JAXBElement<String>(_Reserved2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reserved4")
    public JAXBElement<String> createReserved4(String value) {
        return new JAXBElement<String>(_Reserved4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OpRetMsg")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOpRetMsg(String value) {
        return new JAXBElement<String>(_OpRetMsg_QNAME, String.class, null, value);
    }

}
